=== FindMyFriends/api/App/V1/Demands/schema/post.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "additionalProperties": false,
    "properties": {
        "body": {
            "additionalProperties": false,
            "properties": {
                "weight": {
                    "type": [
                        "integer",
                        "null"
                    ]
                },
                "height": {
                    "type": [
                        "integer",
                        "null"
                    ]
                },
                "build_id": {
                    "type": {
                        "0": [
                            "integer",
                            "null"
                        ],
                        "enum": [
                            null,
                            1,
                            2
                        ]
                    }
                },
                "skin_color_id": {
                    "type": {
                        "0": [
                            "integer",
                            "null"
                        ],
                        "enum": [
                            null,
                            145,
                            8
                        ]
                    }
                }
            },
            "required": [
                "weight",
                "height",
                "build_id",
                "skin_color_id"
            ],
            "type": "object"
        },
        "hair": {
            "additionalProperties": false,
            "properties": {
                "highlights": {
                    "type": [
                        "boolean",
                        "null"
                    ]
                },
                "length": {
                    "additionalProperties": false,
                    "properties": {
                        "value": {
                            "type": [
                                "number",
                                "null"
                            ]
                        },
                        "unit": {
                            "type": [
                                "null",
                                "string"
                            ],
                            "enum": [
                                null,
                                "mm",
                                "cm"
                            ]
                        }
                    },
                    "type": "object",
                    "required": [
                        "value",
                        "unit"
                    ]
                },
                "nature": {
                    "type": [
                        "boolean",
                        "null"
                    ]
                },
                "roots": {
                    "type": [
                        "boolean",
                        "null"
                    ]
                },
                "style": {
                    "type": [
                        "string",
                        "null"
                    ]
                },
                "color_id": {
                    "type": {
                        "0": [
                            "integer",
                            "null"
                        ],
                        "enum": [
                            null,
                            12,
                            10,
                            8
                        ]
                    }
                }
            },
            "required": [
                "roots",
                "length",
                "highlights",
                "nature",
                "style",
                "color_id"
            ],
            "type": "object"
        },
        "face": {
            "additionalProperties": false,
            "properties": {
                "beard": {
                    "additionalProperties": false,
                    "properties": {
                        "length": {
                            "additionalProperties": false,
                            "properties": {
                                "value": {
                                    "type": [
                                        "number",
                                        "null"
                                    ]
                                },
                                "unit": {
                                    "type": [
                                        "null",
                                        "string"
                                    ],
                                    "enum": [
                                        null,
                                        "mm",
                                        "cm"
                                    ]
                                }
                            },
                            "type": "object",
                            "required": [
                                "value",
                                "unit"
                            ]
                        },
                        "style": {
                            "additionalProperties": false,
                            "type": [
                                "string",
                                "null"
                            ]
                        },
                        "color_id": {
                            "type": {
                                "0": [
                                    "integer",
                                    "null"
                                ],
                                "enum": [
                                    null,
                                    12,
                                    8
                                ]
                            }
                        }
                    },
                    "type": "object",
                    "required": [
                        "length",
                        "style",
                        "color_id"
                    ]
                },
                "care": {
                    "$ref": "#/definitions/rating"
                },
                "eyebrow": {
                    "additionalProperties": false,
                    "properties": {
                        "id": {
                            "type": "integer"
                        },
                        "care": {
                            "$ref": "#/definitions/rating"
                        },
                        "color_id": {
                            "type": {
                                "0": [
                                    "integer",
                                    "null"
                                ],
                                "enum": [
                                    null,
                                    12,
                                    8
                                ]
                            }
                        }
                    },
                    "required": [
                        "care",
                        "color_id"
                    ],
                    "type": "object"
                },
                "freckles": {
                    "type": [
                        "boolean",
                        "null"
                    ]
                },
                "eye": {
                    "additionalProperties": false,
                    "properties": {
                        "left": {
                            "$ref": "#/definitions/eye"
                        },
                        "right": {
                            "$ref": "#/definitions/eye"
                        }
                    }
                },
                "shape": {
                    "type": [
                        "string",
                        "null"
                    ],
                    "enum": [
                        null,
                        "oval",
                        "long",
                        "round",
                        "square"
                    ]
                },
                "teeth": {
                    "additionalProperties": false,
                    "properties": {
                        "braces": {
                            "type": [
                                "boolean",
                                "null"
                            ]
                        },
                        "care": {
                            "$ref": "#/definitions/rating"
                        }
                    },
                    "required": [
                        "care",
                        "braces"
                    ],
                    "type": "object"
                }
            },
            "required": [
                "beard",
                "teeth",
                "shape",
                "care",
                "eye",
                "eyebrow",
                "freckles"
            ],
            "type": "object"
        },
        "general": {
            "additionalProperties": false,
            "properties": {
                "age": {
                    "additionalProperties": false,
                    "properties": {
                        "from": {
                            "type": [
                                "integer",
                                "null"
                            ],
                            "minimum": 15,
                            "maximum": 130
                        },
                        "to": {
                            "type": [
                                "integer",
                                "null"
                            ],
                            "minimum": 15,
                            "maximum": 130
                        }
                    },
                    "required": [
                        "from",
                        "to"
                    ],
                    "type": "object"
                },
                "firstname": {
                    "type": [
                        "string",
                        "null"
                    ]
                },
                "gender": {
                    "type": "string",
                    "enum": [
                        "man",
                        "woman"
                    ]
                },
                "lastname": {
                    "type": [
                        "string",
                        "null"
                    ]
                },
                "race_id": {
                    "type": {
                        "0": [
                            "integer",
                            "null"
                        ],
                        "enum": [
                            null,
                            1,
                            2,
                            3
                        ]
                    }
                }
            },
            "required": [
                "lastname",
                "firstname",
                "age",
                "gender",
                "race_id"
            ],
            "type": "object"
        },
        "hands": {
            "additionalProperties": false,
            "properties": {
                "nails": {
                    "additionalProperties": false,
                    "properties": {
                        "length": {
                            "additionalProperties": false,
                            "properties": {
                                "value": {
                                    "type": [
                                        "number",
                                        "null"
                                    ]
                                },
                                "unit": {
                                    "type": [
                                        "null",
                                        "string"
                                    ],
                                    "enum": [
                                        null,
                                        "mm",
                                        "cm"
                                    ]
                                }
                            },
                            "type": "object",
                            "required": [
                                "value",
                                "unit"
                            ]
                        },
                        "care": {
                            "$ref": "#/definitions/rating"
                        },
                        "color_id": {
                            "type": {
                                "0": [
                                    "integer",
                                    "null"
                                ],
                                "enum": [
                                    null,
                                    145,
                                    12,
                                    10,
                                    8
                                ]
                            }
                        }
                    },
                    "required": [
                        "length",
                        "care",
                        "color_id"
                    ],
                    "type": "object"
                },
                "care": {
                    "$ref": "#/definitions/rating"
                },
                "vein_visibility": {
                    "$ref": "#/definitions/rating"
                },
                "joint_visibility": {
                    "$ref": "#/definitions/rating"
                },
                "hair": {
                    "additionalProperties": false,
                    "properties": {
                        "amount": {
                            "additionalProperties": false,
                            "type": [
                                "integer",
                                "null"
                            ]
                        },
                        "color_id": {
                            "type": {
                                "0": [
                                    "integer",
                                    "null"
                                ],
                                "enum": [
                                    null,
                                    12,
                                    8
                                ]
                            }
                        }
                    },
                    "required": [
                        "amount",
                        "color_id"
                    ],
                    "type": "object"
                }
            },
            "required": [
                "nails",
                "care",
                "vein_visibility",
                "joint_visibility",
                "hair"
            ],
            "type": "object"
        },
        "location": {
            "additionalProperties": false,
            "properties": {
                "coordinates": {
                    "additionalProperties": false,
                    "properties": {
                        "latitude": {
                            "type": "number"
                        },
                        "longitude": {
                            "type": "number"
                        }
                    },
                    "required": [
                        "latitude",
                        "longitude"
                    ],
                    "type": "object"
                },
                "met_at": {
                    "additionalProperties": false,
                    "properties": {
                        "moment": {
                            "type": [
                                "string",
                                "null"
                            ],
                            "format": "date-time"
                        },
                        "timeline_side": {
                            "type": [
                                "string",
                                "null"
                            ],
                            "enum": [
                                "exactly",
                                "sooner",
                                "later",
                                "sooner or later"
                            ]
                        },
                        "approximation": {
                            "type": [
                                "string",
                                "null"
                            ]
                        }
                    },
                    "required": [
                        "moment",
                        "timeline_side",
                        "approximation"
                    ],
                    "type": "object"
                }
            },
            "required": [
                "coordinates",
                "met_at"
            ],
            "type": "object"
        }
    },
    "required": [
        "location",
        "general",
        "face",
        "hair",
        "body",
        "hands"
    ],
    "type": "object",
    "definitions": {
        "rating": {
            "type": [
                "integer",
                "null"
            ],
            "minimum": 0,
            "maximum": 10
        },
        "eye": {
            "additionalProperties": false,
            "properties": {
                "id": {
                    "type": "integer"
                },
                "lenses": {
                    "type": [
                        "boolean",
                        "null"
                    ]
                },
                "color_id": {
                    "type": {
                        "0": [
                            "integer",
                            "null"
                        ],
                        "enum": [
                            null,
                            12,
                            10,
                            8
                        ]
                    }
                }
            },
            "required": [
                "lenses",
                "color_id"
            ],
            "type": "object"
        }
    }
}

=== FindMyFriends/api/Tests/fixtures/samples/demand/put.json
{
  "general": {
    "age": {
      "from": 16,
      "to": 20
    },
    "gender": "man",
    "race_id": 2,
    "firstname": "Dominik",
    "lastname": "Klapuch"
  },
  "hair": {
    "style": "normal",
    "color_id": 8,
    "length": {
      "value": 20,
      "unit": "mm"
    },
    "highlights": false,
    "roots": true,
    "nature": false
  },
  "face": {
    "teeth": {
      "care": 5,
      "braces": false
    },
    "freckles": false,
    "beard": {
      "color_id": 8,
      "length": {
        "value": 2,
        "unit": "mm"
      },
      "style": "none"
    },
    "shape": "oval",
    "care": 10,
    "eyebrow": {
      "color_id": 8,
      "care": 2
    },
    "eye": {
      "left": {
        "color_id": 8,
        "lenses": false
      },
      "right": {
        "color_id": 8,
        "lenses": false
      }
    }
  },
  "body": {
    "build_id": 1,
    "skin_color_id": 8,
    "weight": 60,
    "height": 181
  },
  "location": {
    "coordinates": {
      "latitude": 50.1,
      "longitude": 50.2
    },
    "met_at": {
      "moment": "2017-01-01T13:58:10+00:00",
      "timeline_side": "sooner",
      "approximation": "PT3H"
    }
  },
  "hands": {
    "nails": {
      "color_id": null,
      "length": {
        "value": null,
        "unit": "mm"
      },
      "care": null
    },
    "care": 10,
    "vein_visibility": 5,
    "joint_visibility": 1,
    "hair": {
      "color_id": 8,
      "amount": 5
    }
  }
}
